# Site settings
title: Myung Jin's portfolio
description: 
baseurl: ""
url: "https://eoqkrskfk94.github.io"

# User settings
username: 김명진 Myung Jin Kim
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Software Developer
email: "eoqkrskfk94@gmail.com"
twitter_username: 
github_username:  "https://github.com/eoqkrskfk94"
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
